### ISSUE TITLE
README is incorrect, by default won't show up in 'Manage extensions'

### ISSUE THREAD

**Issue by Jeroen52** [phpbb-extensions/camosslimageproxy#3]
When cloning, the name of the folder is 'camo-ssl-image-proxy' which causes the extension not to show up on the disabled extensions list. When changing it to 'camosslimageproxy' it will show up.

Offtopic: I actually got this extension and Camo working on my forum, thank you very much for the people who contributed for eliminating mixed content warnings.

**Comment by michaelcullum** [comment]
Thanks and glad to hear you got it working. :)

**Comment by Jeroen52** [comment]
It took a while, and editing the config in apache, camo and `event/listener.php` to get it working but I'm sure the forum will now stop annoying Internet Explorer users about mixed content.

**Comment by michaelcullum** [comment]
Yeah, it's on the todo list to make those values configurable in the ACP

**Comment by Jeroen52** [comment]
It would make it easier to configure, but I think that just editing the values in a file a little bit is no challenge to those who can get Camo working on a non-Heroku environment which is also really easy for those who know how to do it.

**Comment by Jeroen52** [comment]
Also, wouldn't the dash in the directory name bug out on https://github.com/phpbb-extensions/collapsible-categories ?

**Comment by DavidIQ** [comment]
The releases for that one are packaged correctly and with the phpbb folder included.
