### ISSUE TITLE
Add ACP to extension, move template specifications to database

### ISSUE THREAD

**Issue by v12mike** [phpbb-extensions/camosslimageproxy#5]
I have written code for an ACP page to allow configurability to most aspects of the extension:
* configurable server parameters
* donfigurable list of domains for direct mapping
* configurable list of phpBB template locations where urls might need remapping fro compatibility with other phpBB extensions that may display images.
* move the list of phpBB template locations to the database to allow configurability
* add mode with compatibility with cloudinary.com instead of a camo proxy (useful for testing)

**Comment by Jeroen52** [comment]
Surely you should make a pull request instead of a new issue, right?

**Comment by v12mike** [comment]
I have made a pull request.  Sorry, not very familiar with the etiquette.

**Comment by michaelcullum** [comment]
@v12mike Thanks for the PR, I'll have a look over it. :)

**Comment by DavidIQ** [comment]
@michaelcullum or @VSEphpbb think one of you could give this a look and review? Thanks.
